version: 2

jobs:
  build:
    docker:
      - image: trevorj/circleci-builder:latest
    working_directory: /app

    steps:
      - checkout
      - run:
          name: checkout-submodules
          command: |
            set -eo pipefail
            set -xv
            git submodule sync
            git submodule update --init

      - setup_docker_engine

      - run:
          name: build
          command: |
            set -eo pipefail
            set -xv
            export ${!*}
            make -j10

      #- run:
      #    name: test
      #    command: |
      #      set -eo pipefail
      #      set -xv
      #      export ${!*}
      #      make test

      - deploy:
          name: docker-login
          command: docker login -e "$DOCKER_EMAIL" -u "$DOCKER_USER" -p "$DOCKER_PASS"

      - deploy:
          name: push
          command: |
            set -eo pipefail
            set -xv
            export ${!*}
            case "$CIRCLE_BRANCH" in
                master)
                  make -j10 push
                  make -j10 push DOCKER_REPO=ubuntu-salt-minion
                  ;;
            esac
